export K6_WRITE_HOSTNAME="localhost:8000"
export K6_READ_HOSTNAME="localhost:8007"
export K6_USERNAME="14267"
export K6_SCHEME="http"
export K6_TENANT_ID="14267"
export K6_WRITE_TOKEN="eyJrIjoiMmZmMDQxZTY2YjZjZjM5ZDRiMzM2NzJlYjdhNjM4NDhjYWM0MzJiMiIsIm4iOiJyZW1vdGVXcml0ZSIsImlkIjoxfQ=="
export K6_DURATION_MIN="60"
export K6_READ_TOKEN="eyJrIjoiYWRiNzYwNzJhZjAxMDU1OTY0OTc1ZjgxYzdlYmI1NWMxOWE3N2RkNiIsIm4iOiJsb2FkdGVzdCIsImlkIjoxfQ=="
export K6_RAMP_UP_MIN="10"

export K6_SCRAPE_INTERVAL_SECONDS=1
export K6_WRITE_REQUEST_RATE=50
export K6_WRITE_SERIES_PER_REQUEST=1000

export K6_READ_REQUEST_RATE=2
export K6_READ_SERIES_PER_REQUEST=10
